name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Test
      run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'L00171222'
        git config --global user.email 'L00171222@atu.ie'
        git remote set-url origin https://l00171222.github.io/ReactJS_App_to_test_ChatGPT_Pipeline/    
        npm run deploy